homebrew:
  tap:
    - caskroom/cask
  packages:
    - { name: ansible }
    - { name: nodebrew }
    - { name: brew-cask, state: latest }
    - { name: git }
    - { name: python }
  cask_packages:
    - atom
    - vagrant
    - virtualbox
    - google-chrome
    - google-drive
    # - java
    - dropbox
